name: Publish image to Docker Hub
on:
  push:
    branches: [ "beta" ]
  pull_request:
    branches: [ "beta" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t squamsh/datadrone:beta
      - name: publish
        run: |
          docker login -u squamsh -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push squamsh/datadrone:beta