name: Push - master
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish_image:
    name: Publish docker image latest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t squamsh/datadrone:latest
      - name: publish
        run: |
          docker login -u squamsh -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push squamsh/datadrone:latest
